[package]
name = "rust_sorter"
version = "0.1.0"
authors = ["Lexkane <alexkane.vip@gmail.com>"]
edition = "2018"

[profile.release]
overflow-checks = true

[profile.dev]
opt-level=3

[dependencies]
itertools = "0.8"